[package]
name = "sched-adapter-in-memory"
description = "Adaptadores en memoria para simulación y pruebas."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sched-application.workspace = true
tracing.workspace = true

[dev-dependencies]
sched-domain.workspace = true
sched-solver.workspace = true
tokio.workspace = true

[lints]
workspace = true
